### ISSUE TITLE
Mongock 5 - Null Repository Results

### ISSUE THREAD

**Issue by hashamrasheed** [mongock/mongock#552]
## Description

When using repositories to get the results in Mongock 5 ChangeUnit, I'm getting null results (even though data exists)

## PRIORITY

CRITICAL

### Mongock
- Mongock version: 5.1.0
- Modules involved: Spring Boot 2.1.10.RELEASE, Spring Data MongoDB 2.1.8.RLEASE
- How Mongock is used: Annotation

## Steps to Reproduce

1. Debug ChangeUnit
2. Analyse the results produced
3. Null in all fields when findBy_id or findBy_name is used. findAll works fine and returns expected results:
<img width="727" alt="Screenshot 2022-07-07 at 5 21 26 PM" src="https://user-images.githubusercontent.com/83578143/177772949-91ea7681-f2fa-40eb-b590-6b83afd18157.png">
4. Data also returns fine I use @NonLockGuarded with the repository.

## Behaviour

**Expected behavior:** Repositories should return correct data from MongoDB

**Actual behavior:** Repositories return null fields

**How often the bug happens:** Everytime a ChangeUnit runs

Here's the result when querying data using findBy_id or findBy_Name:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/83578143/177773807-bcf0ae80-da43-4ed3-aaac-fd29e7221717.png">

<img width="851" alt="image" src="https://user-images.githubusercontent.com/83578143/177773903-d793ea40-6ee7-4aeb-b33c-c06f76f1863b.png">

**Comment by dieppa** [comment]
We'll take a look soon, but my first impression is that's related to SpringData or MongoDB driver, rather than Mongock itself. But we'll get back to you as soon as possible.

**Comment by dieppa** [comment]
Hello @hashamrasheed,

## Quick answer 

Annotate your client repository parameter with @NonLockGuarded(RETURN) as follow:
```java
import io.changock.migration.api.annotations.NonLockGuarded;
import static io.changock.migration.api.annotations.NonLockGuardedType.RETURN;

@Execution
public void execution(@NonLockGuarded(RETURN) RevampRepository revampRepository) {
  //TODO
}
```
This approach ensures the lock synchronisation when accessing the database, but still allows the `RevampRepository` to return clean instances of the `RevampDocument`

> You could also annotate the repository class directly, but that's a more intrusive approach. So up to you.

## Extended explanation

Although while debugging it may seem a problem(for which you have described it as CRITICAL), it's not. The reason why is that in order to ensure the correct lock's synchronisation, Mongock works with proxies, so every access to the database is under the lock's protection. Although you see null fields when inspecting those proxies with the debugger, they behaves correctly when using the getters/setters, very much like Spring framework does. 

This is a conservative approach taken by Mongock(as no all the method calls hit the database and need to be synchronised by the lock), and that's why Mongock allows the user to tell him when a proxy is not required. There are 3 levels of  no-lock-required(`NonLockGuarded`).

- **RETURN:** The one we suggest and it means that all the repository's methods are protected by the lock, but the objects returned(in this case RevampDocument) by all its method are clean(no proxies)
- **METHOD:** It means that the repository's methods are not covered by the lock, but the returned objects are proxied and therefor their methods calls are covered by the lock.
- **NONE:** Neither the repository's method are covered by the lock nor the returned objects are proxied


## Clarification
As you noticed, the `findAll` method doesn't return proxies, so you could see the non null fields. That's because Mongock assume that some basic types(such as Collections, Strings, etc.) won't be required to be proxied.

**Comment by hashamrasheed** [comment]
Thanks @dieppa . I ended up using @NonLockGuarded approach. The confusion stemmed from the fact that I didn't see this behaviour while using Mongock's version 4
