### ISSUE TITLE
unique index creation fails with Continuous Backup enabled on Azure Cosmos

### ISSUE THREAD

**Issue by Noel-Jones** [mongock/mongock#556]
We found out the hard way that enabling Continuous Backup on an Azure Cosmos account has some restrictions, specifically (from [https://docs.microsoft.com/en-us/azure/cosmos-db/continuous-backup-restore-introduction](url):

_Azure Cosmos DB API for SQL or MongoDB accounts that create unique index after the container is created aren't supported for continuous backup. Only containers that create unique index as a part of the initial container creation are supported. For MongoDB accounts, you create unique index using extension commands_.

This impacts mongock in that it is unable to create the mongockLock and mongockChangeLog collections. Actually the creations are created but the unique indexes are not. It is neccessary to create the collections manually using the collowing extension comands

````
db.runCommand( { customAction: "CreateCollection", collection: "mongockLock", indexes: [ {key: {_id: 1}, name: "_id_"}, {key: {key: 1}, name: "key_1", unique: true} ] } );

db.runCommand( { customAction: "CreateCollection", collection: "mongockChangeLog", indexes: [ {key: {_id: 1}, name: "_id_"}, {key: {executionId: 1, author: 1, changeId: 1}, name: "executionId_1_author_1_changeId_1", unique: true} ] } );
````

Is is possible for mongck to use these extension commands for Cosmos accounts? 

Of course further use of mongock to create collections, in particular to add indexes to existing collections, will be severly hampered by the restriction but it would be a start to have mongock able to manage it's own collections in this scenario.

**Comment by dieppa** [comment]
Will take a look soon

**Comment by dieppa** [comment]
Hello @Noel-Jones ,

I see that problem due to the CosmoDB's current limitations. That command you provided it will require Mongock to perform some operations we are not comfortable with. We'll investigate that and we'll try to come up with the best solution. However, I don't think this will be done any time soon.

## Workaround
But there is a workaround that I think it will work for you. Mongock provides the option for you to disable the autocreation of the collection. With this configuration, Mongock won't create the collection nor the index. Instead, it will delegate that operation to the user. However, when Mongock is run, it will check the collection and index are created correctly, though, and it will fail if not. You can see more information about it [here](https://docs.mongock.io/v4/advanced-configuration/index.html#index-creation)

Please let us know if that works for you. Thanks!

**Comment by Noel-Jones** [comment]
Thanks for the update @dieppa I'll pass that workaround on to the dev team. However I think they have found a number of things they have had to work around with Cosmos DB and are now looking at a true Mongo solution (with Mongock too I assume). I am happy for you to close this issue if you like. Regards.

**Comment by dieppa** [comment]
Thanks for updating us. We are added that to our roadmap anyway. If that workaround works(or you move to pure MongoDB), we'll keep the priority as it's.

Otherwise(it doesn't work and you decide not to move to pure MongoDB), please let us know and we'll have that into account in the next prioritisation 😃
