### ISSUE TITLE
Injecting beans by name

### ISSUE THREAD

**Issue by thorstenvogel** [mongock/mongock#638]
The `getBean`-Methods in `io.mongock.runner.spring.base.context.SpringDependencyContext` swallow Exceptions, if either beans are not defined or there are multiple instances of beans available (`org.springframework.beans.factory.NoUniqueBeanDefinitionException`). I only found that out by debugging. It would have helped if the error would have been logged.

How is it possible to inject a bean by name into a `ChangeUnit` using Spring Boot Runner?

**Comment by dieppa** [comment]
Hello @thorstenvogel ,

can you tell me which version are you using, please?

**Comment by thorstenvogel** [comment]
I managed to inject my named beans into ChangeUnit-Methods via
```
    @Execution
    public void migrateSomething(@NonLockGuarded
                                                      @Named("namedBean")
                                                      MyBean namedBean) {
        // do something with namedBean
    }
```

The injection mechanism in Mongock does not allow fields to be injected into the class as constructor-parameter as far as i can see.

For the future ist would be great if ChangeUnits could just be Spring beans, utilizing the dependency-injection mechanisms of Spring.

**Comment by dieppa** [comment]
Hello, I didn't answer until now as we have been pretty busy and I saw you managed to make it work. 

Your suggestion is very interesting, but represents important challenges, specially because Mongock proxies the injection for distributed synchronisation's sake. 

On the other hand, I don't think it's that far. As long as I remember, springboot supports `@Named` injections and Mongock should support dependency injection as construction time.

Thanks!
